### ISSUE TITLE
Separate tables for different jobs for reporting

### ISSUE THREAD

**Issue by mchangir** [gluster/fstat#2]
It'll be easier on the eyes to locate a job type in bold, probably as the title of the table, followed by the table mentioning only the node and the time-stamp.

Thinking about it further, a page per job type would be good too.
So, you could show the break-up of the different jobs and the count against the job in the main page, which would then take the user to the job specific page.
eg. the main page would look like
```
Signature                                      Failure count
./tests/basic/gfapi/gfapi-async-calls-test.t   centos6-regression:14, netbsd7-regression:11
```

**Comment by sankarshanmukhopadhyay** [comment]
Are you stating that providing a summary of how much (sorry about the elastic usage of that word) a job is failing across the job_type would be good information to have?

**Comment by mchangir** [comment]
yes, the per job summary could be useful ... it could be that the
problem is more with the test environment/infra than the code or test
itself

maybe the job seldom fails on netbsd7-regression but often on the
centos6-regression or the other way around

Milind

**Comment by nigelbabu** [comment]
I'm not sure what value this adds? Do the number of failures between platforms help in tracking them down?

**Comment by mchangir** [comment]
hmm ... can't think of a good use case for now

**Comment by nigelbabu** [comment]
Closing the issue, then.
