### ISSUE TITLE
"Duration: 1 week" would provide easy understanding with an actual duration

### ISSUE THREAD

**Issue by sankarshanmukhopadhyay** [gluster/fstat#3]
If the period of the 7 days which is being tracked can be mentioned. As an example, for a page that is loaded today, a "until 07Nov" enables the viewer to understand that the numbers go back an actual calendar week. It would also aid in understanding if any activity during the week contributed to the spike/trough of the failures.

**Comment by nigelbabu** [comment]
Does it make sense to give a date range? i.e. last Monday to current day?

**Comment by sankarshanmukhopadhyay** [comment]
Ah! Ok. So, the difference (as far as I can understand it) in my original proposal and yours is - mine proposes a fluid 7 day window. For instance, if I load the page today, it would be "between today/15Nov and 08Nov". In your explanation, you indicate that we'll pin down Monday as the start/end of the week and thus it will continue to be a Mon --> Sun window

**Comment by nigelbabu** [comment]
Yes. And it would let you select a date range. Rather than counting weeks. I think we'd be most productive looking from Mon-Sat in general. What do you think?

**Comment by sankarshanmukhopadhyay** [comment]
I had thought that switching on the ability to select arbitrary ranges of dates would demand that the application archive a larger volume of data to query and retrieve. My original understanding was that the application provides a 7 day sliding snapshot (to begin with).

There's really a subset of things which can be generated from the data. For instance, how many times did a particular NetBSD instance fail for one/many tests across a defined period and so forth.
